timer: 5

#配置的列表
rules:
  "11":
    #模式1是白名单模式，只能下列ID的道具放置，模式2是黑名单模式，禁止放置下列ID的道具
    mode: 1
    list:
      - 265
      - 264
  "12":
    mode: 2
    list:
      - 7

lang1: "不能在该槽位放置."
lang2: "不能在该槽位放置.且背包没有可以放的地方了....自动丢弃到当前坐标"