inv:
  world: []
  world_the_end: []
  world_nether: []

rewards:
  world:
    - "ACMUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\r\n-2-4-0.5"
    - "ADZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\
    \nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\r\n-6-8-0.85"

lang:
  lang1: "目标必须是箱子"
  lang2: "成功设置世界奖励盒子"
  lang3: "必须是OP才能操作"
  lang4: "成功删除世界奖励盒子"
  lang5: "操作成功"
  lang6: "必须手持物品"
  lang7: "为您打开世界奖励盒子"
  lang8: "直接奖励箱子里的东西被拿完了，请等待刷新"


data:
  box:
    - "world-x-y-z"
  box-refresh:
    world: 10000
  box-refresh-next:
    world: 1111111111