General:
  Stats_Tracking: true
  Config_Update_Overwrite: true
Soulbound:
  Show_Name_In_Lore: true
  Feedback_Messages_Enabled: true
  Prevent_Item_Drop: false
  Delete_On_Drop: false
  Allow_Item_Storing: true
  Infinite_Durability: false
  Blocked_Commands: /blockedcommand
  Commands_Bind_When_Used: /enchant