#功能:
#>服务器TPS检测及提示
#>液体流动自动限制
#>红石自动检测及清理
#>作物自动检测及清理
#>自动与手动清理,清理包括实体,怪物,动物.实体清理会保护贵重物品,怪物清理会保护重要怪物,动物清理会保护贵重动物与可选生成相应的动物蛋
#################################
#####       TPS配置         #####
#################################
tps:
  checkInterval: 80         #检测间隔,单位秒
  broadcast: true           #tps改变时是否全服提示
  levels:                   #注:tps在0.0-20.0之间.比如默认设置表示tps在16.0到20.0之间时为非常好,10.0-16.0之间时为良好,0.0-10.0之间时为很差
    unknown:                #未知状态一般出现在服务器刚开启时
      status: "&7未知"
      show: "&2(说明:未知状态)"
    good:
      threshold: 16.0
      status: "&a非常好"
      show: "&2(说明:此状态下如果你仍然感觉卡可能是与服务器&c网络连接不好&2或周围&c建筑较多&2或你的电脑&c配置较差&2)"
    fine:
      threshold: 10.0
      status: "&6良好"
      show: "&2(说明:此状态下请不要使用&c红石&2,不要过量&c养殖&2动物及其它相关操作)"
    bad:
      status: "&c很差"
      show: "&2(说明:此状态说明&c玩家比较多&2或&c动物太多&2或有人使用&c高频红石&2或放置&c大面积流水岩浆&2或&c其它情况&2)"
#################################
#####  液体(流水/岩浆)限制  #####
#################################
liquid:
  enable: true
  checkInterval: 15        #计时周期,单位秒
  times:                   #周期内允许液体流动事件的上限
    good:                  #服务器状态为十分好时
      limit: 5000          #达到多少时取消玩家倒液体
      cancel: 8000         #达到多少直接禁止后续的液体流动事件
    fine:                  #服务器状态为良好时
      limit: 4500
      cancel: 7000
    bad:                   #服务器状态为很差时
      limit: 4000
      cancel: 6000
    unknown:               #服务器状态为未知时
      limit: 5000
      cancel: 8000
  liquidBlock:             #哪些方块是属于液体方块
    - 8
    - 9
    - 10
    - 11
  items:                   #手中拿着什么物品时判定为倒液体
    - 8
    - 9
    - 10
    - 11
    - 326
    - 327
#################################
#####       红石限制        #####
#################################
redstone:
  enable: true
  ignoreWorlds:            #哪些世界不进行检测(大小写敏感)
    - "xxx"
  checkInterval: 100       #计时周期,单位秒
  gridSize: 20             #以多少格分区检测
  drop: false              #true表示掉落,false表示清除(消失)
  allBlocks: false         #true表示忽略removeBlocks设置,所有方块都会进行清理
  removeBlocks:            #哪些ID的方块进行移除(比如清除红石线是比较适合的,但清除按钮,活塞等可能让玩家感觉不好)
    - 55
    - 75
    - 76
    - 93
    - 94
    - 149
    - 150
  reset: false             #每次移除方块后是否重置计数器
  times:
    unknown:               #服务器状态为未知时
      tipTimes: 100
      removeTimes: 140
    good:                  #服务器状态为十分好时
      tipTimes: 100        #每秒红石事件上限,超过时提示,下同
      removeTimes: 140     #每秒红石事件上限,超过时提示+移除方块,然后检测重新计数,下同
    fine:                  #服务器状态为良好时
      tipTimes: 80
      removeTimes: 120
    bad:                   #服务器状态为很差时
      tipTimes: 60
      removeTimes: 100
  tip:
    ingame: true           #游戏内提示
    ingameTipMinInterval: 5000 #游戏内提示的最小间隔,防刷屏,单位毫秒,0表示无间隔
    console: true          #控制台提示
    consoleTipMinInterval: 500 #控制台提示的最小间隔,防刷屏,单位毫秒,0表示无间隔
#################################
#####       作物限制        #####
#################################
#包括(小麦,胡萝卜,马铃薯,甘蔗,仙人掌,西瓜,南瓜)生长事件与蘑菇蔓延事件
crop:                      #作物限制
  enable: false
  ignoreWorlds:            #哪些世界不进行检测(大小写敏感)
    - 
  checkInterval: 20        #检测周期,单位秒
  gridSize: 30             #以多少格分区检测
  max: 30                  #周期内作物事件计数上限
  drop: true               #true表示掉落,false表示清除(消失)
  reset: false             #每次移除方块后是否重置计数器
  tip:
    ingame: false          #游戏内提示
    ingameTipMinInterval: 5000 #游戏内提示的最小间隔,防刷屏,单位毫秒,0表示无间隔
    console: true          #控制台提示
    consoleTipMinInterval: 500 #控制台提示的最小间隔,防刷屏,单位毫秒,0表示无间隔
#################################
#####    自动与手动清理     #####
#################################
clear:
  tip: false               #清理时是否全服通告,false表示只在控制后台提示
  ignoreWorlds:            #哪些世界不进行检测(大小写敏感)
    - 
  checkInterval: 300       #检测间隔,单位秒
  startClearEntitys: 1000  #自动清理检测时,如果服务器实体数量没有达到这个值,则取消清理
  mustClear:
    amount: 5000           #自动清理检测时,如果服务器实体数量达到了这个值,则必然开启清理
    level: 3               #清理等级
  clear:
    unknown:               #服务器状态为未知时,清理等级0
      show: "无"
      entity: false
      monster: false
      animal: false
    good:                  #服务器状态为非常好时,清理等级1
      show: "无"
      entity: false
      monster: false
      animal: false
    fine:                  #服务器状态为良好时,清理等级2
      show: "低级"
      entity: true
      monster: true
      animal: false
    bad:                   #服务器状态为很差时,清理等级3
      show: "高级"
      entity: true
      monster: true
      animal: true
  entity:                  #清除实体
    clear:                 #直接清除的实体列表(实体ID为1表示掉落物,不要写上)
      - 2
      - 10
      - 11
      - 12
      - 20
      - 22
    items:
      ticksLived: 150      #指掉落的物品保护多少tick不被清理,0表示不保护
      mode: 1              #mode为1表示除白名单外都清理,2表示除黑名单外都不清理
      white:
        - 14
        - 15
        - 16
        - 21
        - 22
        - 29
        - 41
        - 42
        - 49
        - 52
        - 56
        - 57
        - 73
        - 74
        - 89
        - 116
        - 122
        - 129
        - 133
        - 138
        - 144
        - 152
        - 153
        - 256
        - 257
        - 258
        - 261
        - 263
        - 264
        - 265
        - 266
        - 267
        - 276
        - 277
        - 278
        - 279
        - 283
        - 284
        - 285
        - 286
        - 292
        - 293
        - 298
        - 299
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        - 309
        - 310
        - 311
        - 312
        - 313
        - 314
        - 315
        - 316
        - 317
        - 319
        - 320
        - 322
        - 325
        - 326
        - 327
        - 328
        - 335
        - 340
        - 342
        - 343
        - 345
        - 347
        - 363
        - 364
        - 365
        - 366
        - 383
        - 384
        - 386
        - 387
        - 388
        - 396
        - 397
        - 399
        - 403
        - 417
        - 418
        - 419
      black:
        - 
  monster:                   #清除怪物
    ske: true                #true表示地狱中的骷髅不清理
    clear:                   #需要清除的怪物ID列表
      - 50
      - 51
      - 52
      - 54
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 66
  animal:                    #清理动物
    gridSize: 30             #以多少格分区检测
    maxPerGrid: 20           #动物每区允许的数量
    firstAll: true           #true表示在检测生成箱子前先进行遍历箱子检测,消耗资源大,但效果更好
    heightMax: 2             #只对firstAll为true的情况有效.值>=0.表示会选择动物的y坐标,遍历整个区的y-heightMin到y+heightMax
    heightMin: 1             #同上,值>=0
    clearTypes:              #需要清除的动物实体ID列表及相应的变成蛋的机率(注意:此机率从0-1000,如100表示100/1000的机率)
      - "90 400"
      - "91 300"
      - "92 200"
      - "93 250"
      - "96 10"
    airBlocks:               #检测方块时被当作空气的方块ID列表,在自动生成箱子时用到,这些方块会被当作空气
      - 0
      - 17
      - 18
      - 31
      - 32
      - 37
      - 38
      - 39
      - 40
      - 59
      - 83
      - 86
      - 106
      - 111