#==========================#
#                          #
#        活跃验证码        #
#                          #
#==========================#

# 每隔多长时间向玩家发送随机数字以验证是否挂机
#    单位: tick
Period_Code: 6000

# 玩家收到验证码后有效回复时间
#    单位: tick
Delay_Code: 600


# 自定义消息
#   %player% 指代玩家
#   %code%   指代验证码
#
# 提醒玩家输入验证码
Message_Notice_Code: "&d请在聊天框中输入数字 &b%code% &d并发送"

# 未在有效回复时间内回复验证码踢出消息
Message_Kick_Code: "&b亲爱的 &d%player% &b，您太长时间没有输入验证码了，请重新连接服务器"

# 有效回复时间剩下15秒时自动发送消息提醒玩家
Message_Notice_FifteenSec_Code: "&d注意！若您在15秒钟内仍未输入验证码，将被踢出服务器"

# 验证成功消息
Message_Success: "&a验证成功！请继续游玩."