#指令,%player%代替玩家%message%代替消息
#player:代表以玩家发送, console:代表后台, op:代表玩家以op权限
command: "op:say %message%"
#当玩家使用完成后发送什么消息
complete: "成功发送"

#界面的提示
titles:
  #上方字样，彩色用§
  title:
    - "默认字符"
  #输入栏描述字样
  x1: -1
  y1: 30
  subtitle:
    - "默认描述"
  x2: -1
  y2: 160


#消耗物品
require: true

bg:
  #UI背景图片位置([local]什么的或者地址)
  url: "背景url写在这里"
  #背景图片宽度（像素)
  width: 0
  #背景图片高度（像素）
  height: 0
  
button:
  #id，这里只要不重复任何数字都可以
  #用指令创建会自动帮你随机
  id: 
  #按钮字样
  text: "默认按钮"
  #两个按钮图片
  normal: "默认普通按钮图片.jpg"
  hover: "默认悬浮按钮图片.jpg"
  #按钮图片宽度
  width: 0
  #按钮图片高度
  height: 0
  #输入栏里的空格用什么代替(有些指令不支持空格)
  char: " "
  x: 350
  y: 160
txt:
  #同上面id，只要不一样什么都可以，也会自动随机
  id: 
  #输入栏最高能有多少个字符
  char: 20
  x: 40
  y: 180
  w: 300

#不用理他
  item: