plugin:
  debug: false
  delay: 10
  max-db-connection: 8

sync:
  health: true
  food: true
  exp: true
  inventory: true
  chest: true
  potion: true

kick-load-failed: true
kick-load-message: Your game data loading error, please contact the operator
