license: "xxxxxxx"

#从2.0开始不用插件内的语言文件了，请直接汉化神奇宝贝mod



#模式1从本配置文件读取中文
#模式2从神奇宝贝配置文件中读取中文，但是读取的非常不完整！！！！！！！（有效率20%以下）
mode: 1


#插件内语言文件....自己填坑吧
#KEY必须小写
lang:
  "wingull": "§e你妈的信天翁"

  "adamant": "固执"
  "bashful": "害羞"
  "bold": "大胆"
  "brave": "勇敢"
  "calm": "温和"
  "careful": "慎重"
  "docile": "坦率"
  "gentle": "温顺"
  "hardy": "勤奋"
  "hasty": "急躁"
  "impish": "淘气"
  "jolly": "爽朗"
  "lax": "乐天"
  "lonely": "怕寂寞"
  "mild": "慢吞吞"
  "modest": "内敛"
  "naive": "天真"
  "naughty": "顽皮"
  "quiet": "冷静"
  "quirky": "浮躁"
  "rash": "马虎"
  "relaxed": "悠闲"
  "sassy": "自大"
  "serious": "认真"
  "timid": "胆小"

  "microscopic": "袖珍"
  "pygmy": "迷你"
  "runt": "侏儒"
  "small": "娇小"
  "ordinary": "普通"
  "huge": "高大"
  "giant": "巨人"
  "enormous": "庞大"
  "ginormous": "巨大"

  "skill1": "技能1"
