name: Deadbolt
main: com.daemitus.deadbolt.DeadboltPlugin
version: 2.2
authors: [daemitus, md_5]
description: A simple plugin for locking containers and doors without passwords or database files. Recreated from Acru's original plugin.

commands:
  deadbolt:
    description: Access to the Deadbolt plugin via commands.
    aliases: db

permissions:
#------------------------------------------------------------------------------#
  deadbolt.*:
    description: All user and admin functionality INCLUDING broadcasts and commands
    default: op
    children:
      deadbolt.user.*: true
      deadbolt.admin.*: true
      deadbolt.broadcast.*: true
      deadbolt.command.*: true
#------------------------------------------------------------------------------#
  deadbolt.user.*:        
    description: All user functionality
    default: op
    children:          
      deadbolt.user.create.*: true
      deadbolt.user.color: true
#------------------------------------------------------------------------------#
  deadbolt.user.color:
    description: Allows coloring of signs
    default: op
#------------------------------------------------------------------------------#
  deadbolt.user.create.*:
    description: Allows protection of all chests, dispensers, furnaces, doors, and trapdoors
    default: true
    children:
      deadbolt.user.create.chest: true
      deadbolt.user.create.dispenser: true
      deadbolt.user.create.door: true
      deadbolt.user.create.furnace: true
      deadbolt.user.create.trapdoor: true
      deadbolt.user.create.trappedchest: true
      deadbolt.user.create.fencegate: true
      deadbolt.user.create.brewery: true
      deadbolt.user.create.cauldron: true
      deadbolt.user.create.enchant: true
  deadbolt.user.create.chest:
    description: Allows user protection of chests
    default: true
  deadbolt.user.create.dispenser:
    description: Allows user protection of dispensers
    default: true
  deadbolt.user.create.door:
    description: Allows user protection of doors
    default: true
  deadbolt.user.create.furnace:
    description: Allows user protection of furnaces
    default: true
  deadbolt.user.create.trapdoor:
    description: Allows user protection of trapdoors
    default: true
  deadbolt.user.create.trappedchest:
    description: Allows user protection of trapped chests
    default: true
  deadbolt.user.create.fencegate:
    description: Allows user protection of fencegates
    default: true
  deadbolt.user.create.brewery:
    description: Allows user protection of brewing stands
    default: true
  deadbolt.user.create.cauldron:
    description: Allows user protection of cauldrons
    default: true
  deadbolt.user.create.enchant:
    description: Allows user protection of enchantment tables
    default: true
#------------------------------------------------------------------------------#
  deadbolt.admin.*:
    description: Allows for all admin functionality
    default: op
    children:
      deadbolt.admin.create: true
      deadbolt.admin.break: true
      deadbolt.admin.bypass: true
      deadbolt.admin.commands: true
      deadbolt.admin.snoop: true
  deadbolt.admin.create:
    description: Allows admin protection of all for other users
    default: op
  deadbolt.admin.break:
    description: Allows admin breaking of protected blocks
    default: op
  deadbolt.admin.bypass:
    description: Allows admin usage of protected doors and trapdoors
    default: op
  deadbolt.admin.commands:
    description: Allows admin usage of commands on user blocks
    default: op
  deadbolt.admin.snoop:
    description: Allows admin usage of protected chests, dispensers, and furnaces
    default: op
#------------------------------------------------------------------------------#
  deadbolt.command.*:
    description: Allows use of all priviledged commands
    default: op
    children:
      deadbolt.command.reload: true
  deadbolt.command.reload:
    description: Allows admin usage of /deadbolt reload
    default: op
#------------------------------------------------------------------------------#
  deadbolt.broadcast.*:
    description: Receives all notifications of admin overrides
    default: op
    children:
      deadbolt.broadcast.break: true
      deadbolt.broadcast.snoop: true
  deadbolt.broadcast.break:
    description: Receives notifications of admin override block breaks
    default: op
  deadbolt.broadcast.snoop:
    description: receives notifications of admin override container snoops
    default: op
#------------------------------------------------------------------------------#
