#提示内容
lang:
  lang1: "§c%player% §b发起了精灵竞争, 你可以输入/pkr join花费1000金币进行匹配竞争"
  lang2: "§c你成功加入精灵竞争"
  lang3: "§b你取消了精灵竞争,金币已返还"
  lang4: "§b精灵竞争开始了!本次队伍玩家1:%player_1%玩家2:%player_2%玩家3:%player_3%玩家4:%player_4%"
  lang5: "§c你失败了精灵竞争,你输掉了1000金币"
  lang6: "§a你胜利了精灵竞争,你获得了4000金币"
  lang7: "§a匹配时间过长,未能匹配到对手,已自动取消精灵竞争,金币已返还"
  lang8: "§e本次进行竞争平局,金币已返还"
  #lang9: "§a对手逃离战场,你成功获得了4000金币"
  #lang10: "§a你离开了精灵竞争,你被默认判断失败,你输掉了1000金币"
  lang11: "§b插件配置重载完成!"
  lang12: "你已经加入过了"
  lang13: "你不在匹配中"
  lang14: "金币不足，无法加入"
#参赛需要消耗的金币 需要拥有经济插件作为前置
cost: 1000.00
#匹配等待时间 超过此时间自动停止继续匹配 以秒计时
matching: 320

command:
  win:
    - "t %player% 加油！你是最棒的精灵战士！"
    - "eco give %player% 4000"
  fail:
    - "t %player% 加油!下次再接再厉！"
  cancel:
    - "t %player% 平局！"