jdbc:
  driver: "com.mysql.jdbc.Driver"
  url: "jdbc:sqlite:!dir!/data.db"
  username: "root"
  password: "1q2w3e4r"

lang:
  lang1: "§4§l您要加入的比赛不存在"
  lang2: "§c§l缺少参数"
  lang3: "§c§l服务器未准备就绪,可能是距离上一场游戏结束还不足§a§l10§c§l秒"
  lang4: "§a§l参赛申请成功!"
  lang5: "§a§l您已经报名了一场锦标赛,请等待比赛结束或退赛再报名本场比赛"
  lang6: "§a§l退赛申请已提交"
  lang7: "§a§l您所报名的锦标赛开始啦！"
  lang8: "§c§l锦标赛已开始无法退赛"
  lang9: "§5§l第§f§l%s§5§l轮战斗已经结束..."
  lang10: "§c§l您报名的锦标赛人数不足已取消"
  lang11: "§a§l封禁成功,结束时间§f§l%s"
  lang12: "§c§l锦标赛已开始无法加入"
  lang13: "§a§l强制操作已提交"
  lang14: "§a§l即将在§f§l%s§a§l秒后开始下一轮战斗,请及时准备否则将直接判输"
  lang15: "§c§l你未报名游戏或者游戏不在开始阶段"
  lang16: "§a§l准备已成功!"
  lang17: "§6§l等待时间已到.本轮还有§f§l%s§6§l名选手参加"
  lang18: "§a§l恭喜你被抽中在本轮不用战斗直接晋级到下一轮"
  lang19: "§6§l恭喜玩家§f§l%s§6§l抽中在本轮不用战斗直接晋级下一场"
  lang20: "§c§l回合最长时间已到,未完成本轮比赛的玩家直接全部淘汰"
  lang21: "§c§l对阵: 玩家§f§l%s§c§l与玩家§f§l%s"
  lang22: "§c§l玩家§f§l%s§c§l在本回合战斗中胜利了"
  lang23: "§c§l玩家§f§l%s§c§l在本回合战斗中失败了"
  lang24: "§c§l玩家§f§l%s§c§l最终被淘汰了"
  lang25: "§c§l玩家§f§l%s§c§l未及时准备而被淘汰"
  lang26: "§c§l游戏人数超过上限,无法加入"
  lang27: "§c§l游戏尚未开始报名,无法加入"
  lang28: "§c§l游戏已经结束报名,无法加入"
  lang29: "§c§l不允许两只同编号精灵,您已被淘汰！"
  lang30: "§c§l出现了禁止的精灵!您已被淘汰！"
  lang31: "恭喜玩家%s获得第%s名的好成绩!"
  lang32: "权限不足"